server:
  port: 8070

spring:
  application:
    name: spring-cloud-admin-server
#  security:
#    user:
#      name: javakc
#      password: 123456

  boot:
    admin:
      ui:
        title: 汇才同飞
      notify:
        pagerduty:
          client-url: http://127.0.0.1:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/,http://127.0.0.1:8002/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10