server:
  port: 8050

spring:
  application:
    name: spring-cloud-config-server

#  native 本地仓库配置
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: /config

#  master git仓库配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhouhonggang/spring-cloud-javakc.git
          searchPaths: /config
      label: master

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    # eureka client发送心跳给eureka server端的频率，默认为30秒
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/,http://${eureka.instance.hostname}:8002/eureka/

info:
  app:
    name: "@project.name.config@"
    description: "@project.description.config@"
    version: "@project.version.config@"